# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  poneidentityapi:
    image: uillian/pone.com:poneidentityapi
    build:
      context: .
      dockerfile: .\POne.Identity.Api\Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./docker-compose.env
    networks:
      poneapi:
        ipv4_address: "192.168.0.51"
    extra_hosts:
      - "pone.financialapi.com:192.168.0.52"
      - "pone.notifierapi.com:192.168.0.53"
      - "pone.sqlserver:192.168.0.54"
    volumes:
      - ./ssl:/app/ssl
      - ./scripts:/app/scripts
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
    depends_on:
      - ponesqlserver
    entrypoint: ["./scripts/wait-for-it.sh", "pone.sqlserver:1433", "-t", "120", "--", "dotnet", "POne.Identity.Api.dll"]

  ponefinancialapi:
    image: uillian/pone.com:ponefinancialapi
    build:
      context: .
      dockerfile: .\POne.Financial.Api\Dockerfile
    ports:
      - 6001:6001
    networks:
      poneapi:
        ipv4_address: "192.168.0.52"
    extra_hosts:
      - "pone.com:192.168.0.51"
      - "pone.notifierapi.com:192.168.0.53"
      - "pone.sqlserver:192.168.0.54"
    volumes:
      - ./ssl:/app/ssl
      - ./scripts:/app/scripts
    depends_on:
      - ponesqlserver
      - ponenotifierapi
      - poneidentityapi
    environment:
      - ASPNETCORE_URLS=https://+:6001;http://+:6000
    env_file:
      - ./docker-compose.env

    entrypoint: ["./scripts/wait-for-it.sh", "pone.sqlserver:1433", "-t", "120", "--", "dotnet", "POne.Financial.Api.dll"]

  ponenotifierapi:
    image: uillian/pone.com:ponenotifierapi
    build:
      context: .
      dockerfile: .\POne.Notifier.Api\Dockerfile
    ports:
      - 7001:7001
    networks:
      poneapi:
        ipv4_address: "192.168.0.53"
    extra_hosts:
      - "pone.com:192.168.0.51"
      - "pone.financialapi.com:192.168.0.52"
      - "pone.sqlserver:192.168.0.54"
    volumes:
      - ./ssl:/app/ssl
      - ./scripts:/app/scripts
    depends_on:
      - ponesqlserver
      - poneidentityapi
    environment:
      - ASPNETCORE_URLS=https://+:7001;http://+:7000
    env_file:
      - ./docker-compose.env
    entrypoint: ["./scripts/wait-for-it.sh", "pone.sqlserver:1433", "-t", "120", "--", "dotnet", "POne.Notifier.Api.dll"]

  ponesqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "SQLDocker98-"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    networks:
      poneapi:
        ipv4_address: "192.168.0.54"
    ports:
      - 1833:1433
    volumes:
      - ~/pone/pone.sqlserver:/var/opt/mssql/data

networks:
  poneapi:
    attachable: true
    driver: overlay
    external: false
    ipam:
      config:
        - subnet: "192.168.0.0/24"